# resources:
# http://www.ameyalokare.com/docker/2017/09/20/nginx-flask-postgres-docker-compose.html
# https://github.com/juggernaut/nginx-flask-postgres-docker-compose-example
# https://serverfault.com/questions/783806/docker-how-to-django-uwsgi-gunicorn-nginx/787402
# https://github.com/andrecp/django-tutorial-docker-nginx-postgres
# https://github.com/realpython/dockerizing-django
# http://ruddra.com/2016/08/14/docker-django-nginx-postgres/index.html
# https://stackoverflow.com/questions/32180589/docker-how-to-expose-a-socket-over-a-port-for-a-django-application


version: '3'

services:

  db:
    image: postgres
    #environment:
     # - POSTGRES_USER:admin
     # - POSTGRES_PASSWORD:success123
     # - POSTGRES_DB:drf_db
    ports:
     - "5432:5432"
    networks:
     - nginx_network

    volumes:
     - ./docker/postgresql/data:/var/lib/postgresql/data

  # web container, with django + gunicorn
  drf_rest:
   build: .
   environment:
     - DJANGO_SETTINGS_MODULE
     - "VIRTUAL_HOST:drf.rest.org"
   volumes:
     - .:/opt/services/django_rest/src
     - static:/opt/services/django_rest/static
     - media:/opt/services/django_rest/media 
   hostname: "drf.rest.org"
   networks:
     - nginx_network
   depends_on:
     - db



  #django_blog:
  #   image: successanil/docker-blog-tutorial-n
  #   volumes:
  #    - staticp:/opt/services/django_project/staticp

  #   hostname: "django.blog.org"
  #   networks:
  #    - nginx_network
  #   depends_on:
  #    - db




  #node_blog:
  #   image: successanil/node-app
  #   networks:
  #    - nginx_network
  #   depends_on:
  #    - db
  #    - drf_rest
 

  # reverse proxy container (nginx)
  nginx:
    image: nginx:1.13
    ports:
#      - 80:80
      - 9002:9002
    #  - 3000:3000
   #   - 9001:9001
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
     # - staticp:/opt/services/django_project/staticp
      - static:/opt/services/django_rest/static
      #- media:/opt/services/django_project/media
      - media:/opt/services/django_rest/media
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - nginx_network
    depends_on:
      - drf_rest
      #- node_blog
      #- django_blog
      - db
    

networks:
  nginx_network:
    driver: bridge

volumes:
  static:
  #staticp:
  media:
